#
# BASE artifact
#
FROM 84codes/crystal:1.20.2-ubuntu-24.04 AS base

#
# BUILDER artifact
#
FROM base AS builder

RUN mkdir -p /crystal-iso8583/lib

WORKDIR /crystal-iso8583/lib

COPY ./shard* /crystal-iso8583/lib/

RUN shards install

COPY ./ /crystal-iso8583/lib

#
# SERVICE
#
FROM builder AS service

ENV image_name=crystal-iso8583

WORKDIR /crystal-iso8583/lib
